apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gatewayx.fullname" . }}-config
  labels:
    {{- include "gatewayx.labels" . | nindent 4 }}
data:
  gatewayx.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
